version: "3.8"

services:
  app:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TOKEN_SECRET=p1x@fl0w@#$