"""tabelas_tarefas_usuarios

Revision ID: ae14dc7af6d9
Revises: c035ef95c9a7
Create Date: 2025-01-09 02:58:29.597103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae14dc7af6d9'
down_revision: Union[str, None] = 'c035ef95c9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Criação da tabela usuarios
    op.create_table(
        'usuarios',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('usuario', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(length=50), nullable=False),
        sa.Column('senha_criptografada', sa.String(length=50), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=False),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=False)
    ) 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###

